version: '3.6'
services:
  web:
    image: docker-node-example
    environment:
      NODE_ENV: qa
    ports:
      - 6000:6011
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
